#!/usr/bin/env -S uv run --script
# /// script
# dependencies = []
# ///
"""PreToolUse hook: blocks edits to protected paths and dangerous bash.

Exit 2 blocks the tool call and feeds stderr back to Claude as guidance.
Exit 0 allows it. Exit 1 does NOT block (common footgun); avoid.

Policy:
- Hard-blocked: auth, routing, ORM base, app entry, AdaLab identity files
  (app.json, project.json), .vscode, Containerfile, lockfiles, .claude
  meta-config, secrets.
- Editable but documented as sensitive in CLAUDE.md: requirements.txt,
  pyproject.toml, frontend/package.json, .adalab/local_container_demo.json,
  frontend/src/styles/tokens.css.
- Dangerous bash (rm -rf, curl|sh, git push) is hard-blocked. Dependency-add
  commands are routed through settings.json `permissions.ask` instead, so the
  human approves each one in-session.
"""

import json
import os
import re
import sys

PROTECTED_PATHS = [
    # Backend infrastructure (auth, routing, ORM base, app entry)
    r"^app/core/",
    r"^app/api/main\.py$",
    r"^app/api/deps\.py$",
    r"^app/models/base\.py$",
    r"^main\.py$",
    # Frontend infrastructure (AdaLab routing, auth-aware client, app entry, build)
    r"^frontend/src/lib/basepath\.ts$",
    r"^frontend/src/api/client\.ts$",
    r"^frontend/src/main\.tsx$",
    r"^frontend/vite\.config\.ts$",
    # Lockfiles — autogenerated; agent edits package.json / pyproject.toml,
    # then regenerates locks via the package manager.
    r"^uv\.lock$",
    r"^frontend/pnpm-lock\.yaml$",
    # Platform identity — port, stripped_prefix, app_name, app_url.
    # local_container_demo.json (env vars, resource limits) is intentionally NOT here.
    r"^\.adalab/app\.json$",
    r"^\.adalab/project\.json$",
    r"^\.vscode/",
    # Build pipeline
    r"^Containerfile$",
    # Claude Code config itself
    r"^\.claude/hooks/",
    r"^\.claude/settings\.json$",
    # Secrets
    r"^\.env(\.|$)",
    r"\.pem$",
    r"\.key$",
]

DANGEROUS_BASH = [
    (r"\brm\s+-[a-z]*r[a-z]*f", "rm -rf variants are blocked"),
    (r"\bcurl\b[^|]*\|\s*(sh|bash)", "curl | shell is blocked"),
    (r"\bgit\s+push\b", "git push is blocked; human will push"),
]


def block(reason: str) -> None:
    print(f"BLOCKED by .claude/hooks/protect_paths.py: {reason}", file=sys.stderr)
    # Also emit JSON that blocks in bypassPermissions mode.
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    sys.exit(2)


def relpath(abs_path: str) -> str:
    base = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    try:
        return os.path.relpath(abs_path, base)
    except ValueError:
        return abs_path


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)  # do not block on malformed input

    tool = data.get("tool_name", "")
    inp = data.get("tool_input", {}) or {}

    if tool in ("Edit", "Write", "MultiEdit"):
        path = inp.get("file_path") or inp.get("path") or ""
        rel = relpath(path)
        for pat in PROTECTED_PATHS:
            if re.search(pat, rel):
                block(f"{rel} is in a protected zone. Ask the human to edit it directly.")

    if tool == "Read":
        path = inp.get("file_path") or ""
        if re.search(r"(^|/)\.env(\.|$)", path) or path.endswith((".pem", ".key", "id_rsa")):
            block(
                "Secret files are not readable. "
                "Reference .env.example if you need environment variable names."
            )

    if tool == "Bash":
        cmd = inp.get("command", "")
        for pat, reason in DANGEROUS_BASH:
            if re.search(pat, cmd):
                block(f"Command matches deny pattern: {reason}")
        # Also block attempts to read protected files via cat/less/head/tail.
        # Strip leading ^ anchors: they're valid when checking relpath() output
        # but break when the pattern is embedded after \b...\b.* mid-regex.
        for pat in PROTECTED_PATHS:
            unanchored = re.sub(r"^\^", "", pat)
            if re.search(rf"\b(cat|less|more|head|tail|bat)\b.*{unanchored}", cmd):
                block("Reading protected file via shell is blocked.")
        if re.search(r"\bcat\b.*\.env", cmd) or re.search(r"\becho\b.*\$\{?[A-Z_]*SECRET", cmd):
            block("Attempt to read or echo secrets is blocked.")

    sys.exit(0)


if __name__ == "__main__":
    main()
