"""Brand assets: the logo is picked up from assets/, and its absence never breaks the app."""
from __future__ import annotations

from core import export, theme
from core import results as R
from tests.conftest import register_student, valid_measurement


def _clear_caches():
    theme.asset_path.cache_clear()
    theme.asset_data_uri.cache_clear()


def test_logo_asset_is_present_and_loadable():
    _clear_caches()
    path = theme.asset_path("cpdse-logo")
    assert path is not None, "assets/cpdse-logo.* should ship with the template"
    uri = theme.logo_uri(prefer_mark=False)
    assert uri and uri.startswith("data:image/")
    assert len(uri) > 200          # actually contains the encoded image


def test_mark_falls_back_to_the_full_logo():
    """Supplying only one file must still brand the whole app."""
    _clear_caches()
    if theme.asset_path("cpdse-mark") is None:
        assert theme.logo_uri(prefer_mark=True) == theme.logo_uri(prefer_mark=False)


def test_missing_assets_degrade_quietly(monkeypatch, tmp_path):
    _clear_caches()
    monkeypatch.setattr(theme, "ASSETS_DIR", tmp_path)   # empty directory
    try:
        assert theme.asset_path("cpdse-logo") is None
        assert theme.logo_uri() is None                   # no exception, just nothing
    finally:
        _clear_caches()


def test_html_report_embeds_the_logo(session):
    _clear_caches()
    m = register_student(session)
    R.submit_result(session, m.id, valid_measurement())
    ctx = export.ReportContext(title="t", course="Chem 101", year="2026", hold=1,
                               group="G1", members=["Ana"], rows=R.query_results(session))
    html = export.build_html_report(ctx)
    assert "data:image/" in html, "the report should carry the brand, it outlives the app"
    assert "Generated by" in html


def test_html_report_still_builds_without_assets(session, monkeypatch, tmp_path):
    _clear_caches()
    monkeypatch.setattr(theme, "ASSETS_DIR", tmp_path)
    try:
        m = register_student(session)
        R.submit_result(session, m.id, valid_measurement())
        ctx = export.ReportContext(title="t", year="2026", hold=1, group="G1",
                                   rows=R.query_results(session))
        html = export.build_html_report(ctx)
        assert "Generated by" in html      # footer present, just no image
    finally:
        _clear_caches()


def test_theme_is_still_the_only_hex_source():
    """assets/ holds artwork; core/theme.py holds every colour the code uses."""
    assert theme.FOREST == "#3C5E3E" and theme.GOLD == "#D6C17C"
